export const errors = {
  MISSING_CHANNEL: 'MISSING_CHANNEL',
  MISSING_CHANNEL_PARAMETERS: 'MISSING_CHANNEL_PARAMETERS',
  NO_CHANNEL_PROVIDED: "NO_CHANNEL_PROVIDED",
  MISSING_MESSAGE_PARAMETERS: "MISSING_MESSAGE_PARAMETERS"
};